local config = require("beads.config")

describe("beads.config", function()
  after_each(function()
    config.setup({})
  end)

  describe("setup", function()
    it("starts from defaults", function()
      config.setup({})
      local cfg = config.get()
      assert.equals("bd", cfg.bd_bin)
      assert.equals("ivy", cfg.picker.theme)
      assert.is_true(cfg.notify)
      assert.is_true(cfg.helpbar)
      assert.equals("rounded", cfg.float.border)
      assert.equals("<C-s>", cfg.mappings.picker.status)
    end)

    it("resets previous setup state", function()
      config.setup({ bd_bin = "/opt/bd" })
      config.setup({})
      assert.equals("bd", config.get().bd_bin)
    end)

    it("deep-merges nested options", function()
      config.setup({ picker = { theme = "dropdown" }, float = { edit = { width = 70 } } })
      local cfg = config.get()
      assert.equals("dropdown", cfg.picker.theme)
      assert.equals(70, cfg.float.edit.width)
      assert.equals(20, cfg.float.edit.height) -- untouched default survives
      assert.equals(96, cfg.float.view.width)
    end)

    it("partial mappings override keeps sibling defaults", function()
      config.setup({ mappings = { view = { edit = "E" } } })
      local m = config.get().mappings
      assert.equals("E", m.view.edit)
      assert.equals("s", m.view.status)
      assert.equals("<C-s>", m.picker.status)
    end)

    it("mapping lhs values replace wholesale, no list merging", function()
      config.setup({ mappings = { view = { quit = { "x" } } } })
      assert.are.same({ "x" }, config.get().mappings.view.quit)
    end)

    it("mapping false disables an action", function()
      config.setup({ mappings = { picker = { status = false } } })
      assert.is_false(config.get().mappings.picker.status)
      assert.are.same({}, config.lhs(config.get().mappings.picker.status))
    end)

    it("keymaps = true expands to defaults", function()
      config.setup({ keymaps = true })
      local km = config.get().keymaps
      assert.equals("<leader>bd", km.base)
      assert.equals("browse", km.menus.l)
    end)

    it("keymaps table: custom base keeps default menus, custom menus replace wholesale", function()
      config.setup({ keymaps = { base = "<leader>B" } })
      assert.equals("<leader>B", config.get().keymaps.base)
      assert.equals("browse", config.get().keymaps.menus.l)

      config.setup({ keymaps = { menus = { z = "ready" } } })
      assert.equals("ready", config.get().keymaps.menus.z)
      assert.is_nil(config.get().keymaps.menus.l)
    end)
  end)

  describe("merge", function()
    it("merges into current options without resetting", function()
      config.setup({ bd_bin = "/opt/bd" })
      config.merge({ picker = { theme = "cursor" } })
      assert.equals("/opt/bd", config.get().bd_bin)
      assert.equals("cursor", config.get().picker.theme)
    end)

    it("composes with setup in either order (extension setup case)", function()
      config.merge({ list_limit = 50 })
      assert.equals(50, config.get().list_limit)
      assert.equals("bd", config.get().bd_bin)

      config.setup({ bd_bin = "/opt/bd" })
      config.merge({ notify = false })
      assert.equals("/opt/bd", config.get().bd_bin)
      assert.is_false(config.get().notify)
    end)

    it("merges mappings per-action", function()
      config.setup({ mappings = { view = { edit = "E" } } })
      config.merge({ mappings = { view = { status = "S" } } })
      local v = config.get().mappings.view
      assert.equals("E", v.edit)
      assert.equals("S", v.status)
      assert.equals("p", v.priority)
    end)
  end)

  describe("lhs", function()
    it("normalizes string, list, false and nil", function()
      assert.are.same({ "q" }, config.lhs("q"))
      assert.are.same({ "q", "<Esc>" }, config.lhs({ "q", "<Esc>" }))
      assert.are.same({}, config.lhs(false))
      assert.are.same({}, config.lhs(nil))
    end)
  end)
end)
